### ISSUE TITLE
Anonymous schema type naming consistency

### ISSUE THREAD

**Issue by genivia-inc** [oasis-tcs/xliff-omos-jliff#13]
The JLIFF schema defines several type names for anonymous objects. The names deviate from the XLIFF spec names, which complicates the drafting of the JLIFF schema.

Suggested naming changes:

- `mtc_translationCandidates` rename to `mtc_matches`
- `mtc_translationCandidatesMatch` rename to `mtc_match`
- `ctr_changeTrackRevisions` rename to `ctr_revisions` 
- `ctr_changeTrackRevisionItem` rename to `ctr_revision`

Suggested merging of global type definition into the parent object type, by inlining into the schema of the parent object:

- `ctr_changeTrackRevisionItemText` merge into `ctr_changeTrackRevisionItem` (i.e. named `ctr_revision `)
- `its_provenanceRecordsWrapper` merge into `its_provenanceRecords` - this wrapper type has no association with the spec prose
- `its_locQualityIssuesWrapper` merge into `its_locQualityIssues` - this wrapper type has no association with the spec prose.
- `gls_glossEntryData` merge into `gls_glossEntry` properties `term` and `definition`

These anonymous object types have a one-to-one correspondence to their parent type, i.e. are single-use only.

**Comment by genivia-inc** [comment]
On a related note, combining the recommended prefix qualification with these suggested renamed produces the following schema type for `mtc_matches`:
~~~
    "mtc_matches": {
      "description": "The translationCandidates module provides a capability to store lists of possible translations along with information about the similarity of the match, the quality of the translation, its provenance, etc.",
      "type": "object",
      "properties": {
        "id": { "$ref": "#/definitions/NMTOKEN" },
        "type": { "$ref": "#/definitions/type", "enum": [ "mtc:match" ] },
        "ref": { "$ref": "#/definitions/NMTOKEN" },
        "translate": { "type": "string", "enum": [ "yes", "no" ] },
        "matches": {
          "type": "array",
          "items": { "$ref": "#/definitions/mtc_match" },
          "minItems": 1
        }
      },
      "additionalProperties": false
    },
~~~
However, XLIFF "5.1.6.2 matches" has no indication that `<matches>` has any attributes, only `<match>` elements.

If so, `id`, `type`, `ref`, and `translate` should be removed and the mtc_matches type simplified to:
~~~
    "mtc_matches": {
      "description": "The translationCandidates module provides a capability to store lists of possible translations along with information about the similarity of the match, the quality of the translation, its provenance, etc.",
          "type": "array",
          "items": { "$ref": "#/definitions/mtc_match" },
          "minItems": 1
      },
      "additionalProperties": false
    },
~~~
Perhaps I am overlooking something. Is this correct?

**Comment by DavidFatDavidF** [comment]
The simplification of `"mtc_matches"` is in order as proposed.

In a way of background:

XLIFF native module wrappers don't have ids and are not referencable, the referencing mechanism is inside the entries within those wrappers.
This is in contrast with the Provenance and Localization Quality issue wrappers that originate from W3C ITS 2.0.

Albeit a single match carries an id to be referencable by the fragid mechanism, it references the relevant core span rather than the other way round. 

 Again in contrast, ITS standoff elements are referenced from the core spans, unlike XLIFF native standoff elements that reference core spans.

**Comment by DavidFatDavidF** [comment]
Reviewed in meeting 25th August
