### ISSUE TITLE
ChangeTrack revision item or items?

### ISSUE THREAD

**Issue by genivia-inc** [oasis-tcs/xliff-omos-jliff#14]
The ChangeTrack XLIFF 2.1 `<ctr:revision>` section 5.6.4.4 is currently mapped to JLIFF 2.1 as follows:
~~~
"ctr_changeTrackRevisionItem": {
      "type": "object",
      "properties": {
        "author": { "type": "string" },
        "dateTime": { "type": "string" },
        "version": { "$ref": "#/definitions/NMTOKEN" },
        "item": { "$ref": "#/definitions/ctr_changeTrackRevisionItemText" }
      },
      "additionalProperties": true
    },

    "ctr_changeTrackRevisionItemText": {
      "type": "object",
      "properties": {
        "property": { "type": "string" },
        "text": { "type": "string" }
      },
      "additionalProperties": true,
      "required": [ "property", "text" ]
    },
~~~
Note that the `item` property in `ctr_changeTrackRevisionItem` is not repeatable (not an array) whereas XLIFF 2.1 `<item>` is repeatable. I assume this should be an `items` array of objects in JLIFF rather than one object. Indeed, section 5.6.44 states that a revision has "One or more <item> elements". The correct way to map this would be to change `item` to `items` containing an array of `ctr_changeTrackRevisionItemText` objects:
~~~
"ctr_changeTrackRevisionItem": {
      "type": "object",
      "properties": {
        "author": { "type": "string" },
        "dateTime": { "type": "string" },
        "version": { "$ref": "#/definitions/NMTOKEN" },
        "items": {
          "type": "array",
          "items": { "$ref": "#/definitions/ctr_changeTrackRevisionItemText" },
          "minitems": 1
        }
      },
      "additionalProperties": true
    },
~~~
When this change is combined with issues #11 and #13, the cumulative change would be:
~~~
    "ctr_revision": {
      "type": "object",
      "properties": {
        "ctr_author": { "type": "string" },
        "ctr_dateTime": { "type": "string" },
        "ctr_version": { "$ref": "#/definitions/NMTOKEN" },
        "ctr_items": { 
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "ctr_property": { "type": "string" },
              "ctr_text": { "type": "string" }
            },
            "additionalProperties": true,
            "required": [ "property", "text" ]
          },
          "minitems": 1
        }
      },
      "additionalProperties": true
    },
~~~
Note that `ctr_revision` has a property `items` that is prefixed as per #11, because `<item>` is defined in section 5.6.4.5 and by convention the JLIFF schema marks properties as plural for arrays. Just to point out that this contrasts other uses of similar properties named `items` in the JLIFF schema which are not prefixed, because these merely serve as placeholders for arrays and have no correspondence to XLIFF elements.

**Comment by DavidFatDavidF** [comment]
The proposed cumulative solution looks good to me

**Comment by DavidFatDavidF** [comment]
I am reopening to clarify in the meeting tomorrow that CTR module only exists in XLIFF Version 2.0 and hence jliff schema variant 2.0.
While CTR **extension** is described within the XLIFF Version 2.1 prose it needs to use the useradata mechanism and (JSON:LD based fully qualified names) as an extension in the JLIFF 2.1 schema variant.

**Comment by DavidFatDavidF** [comment]
Action on Robert to remove ctr_ from JLIFF 2.1 schema variant, agreed in meeting 25th August

**Comment by DavidFatDavidF** [comment]
Reviewed in meeting on 22nd Sep 2020
