### ISSUE TITLE
expressing xml:lang on source and target?

### ISSUE THREAD

**Issue by DavidFatDavidF** [oasis-tcs/xliff-omos-jliff#31]
There's potential schema impact, also related to #30 which will have major schema impact for sure..

**Comment by DavidFatDavidF** [comment]
Option 3) devised for #30 should solve this
To review in the January meeting

**Comment by DavidFatDavidF** [comment]
dF to implement in prose by March meeting

**Comment by genivia-inc** [comment]
Schema 2.0/2.1 [commit Feb.23](https://github.com/oasis-tcs/xliff-omos-jliff/commit/60b29fb4ce9f955163b19a71ea06df262084a695): `sourceXmlLang` and `targetXmlLang` replace `xmlLang` in `segment`, added `sourceXmlLang`, `targetXmlLang` and `targetOrder` to `ignorable`.
