### ISSUE TITLE
Split attribute type into codetype and mrktype

### ISSUE THREAD

**Issue by philr-vistatec** [oasis-tcs/xliff-omos-jliff#54]
Avoid conflicts. They have different data models.

**Comment by genivia-inc** [comment]
Added codeType.xml and mrkType.xml, changed type.xml and updated the corresponding references from ec, sc, ph, sm, unit, group.

**Comment by DavidFatDavidF** [comment]
To be reviewed in meeting tomorrow

**Comment by philr-vistatec** [comment]
Resolved by PR #57
